sudo: required
dist: trusty
os: linux
language: minimal
cache:
  directories:
  - depends/built
  - depends/work
  - depends/sdk-sources
  - $HOME/.ccache
env:
  global:
    - SDK_URL=https://bitcoincore.org/depends-sources/sdks
    - CCACHE_SIZE=1G
    - CCACHE_TEMPDIR=/tmp/.ccache-temp
    - CCACHE_COMPRESS=1
    - MAKEJOBS="-j2"
    - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
    - BASE_PACKAGES="zlib1g-dev zip git build-essential libtool autotools-dev automake pkg-config bsdmainutils curl"
  matrix:
# ARM32
    - HOST=arm-linux-gnueabihf PACKAGES="g++-arm-linux-gnueabihf" OPT="NO_QT=1" CONF="--without-gui"
# ARM64
    - HOST=aarch64-linux-gnu PACKAGES="g++-aarch64-linux-gnu" OPT="NO_QT=1" CONF="--without-gui"
# Win32
    - HOST=i686-w64-mingw32 PACKAGES="g++-mingw-w64-i686 mingw-w64-i686-dev"
# Win64
    - HOST=x86_64-w64-mingw32 PACKAGES="g++-mingw-w64-x86-64 mingw-w64-x86-64-dev"
# x86_64 Linux
    - HOST=x86_64-unknown-linux-gnu PACKAGES=""
# Cross-Mac
    - HOST=x86_64-apple-darwin11 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python-dev" OSX_SDK=10.11

before_install:
    - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
install:
    - sudo add-apt-repository -y ppa:bitcoin/bitcoin
    - sudo apt-get update
    - travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $BASE_PACKAGES
    - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $PACKAGES; fi
before_script:
    - unset CC; unset CXX
    - cd $TRAVIS_BUILD_DIR
    - mkdir -p depends/SDKs depends/sdk-sources
    - if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
    - if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
script:
    - OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
    - ./autogen.sh
    - cd depends && make $MAKEJOBS $OPT
    - cd $TRAVIS_BUILD_DIR && ./configure --prefix=$TRAVIS_BUILD_DIR/depends/$HOST $CONF
    - make $MAKEJOBS
before_deploy:
    - ./pre-deploy.sh
deploy:
  provider: releases
  api_key:
    secure: YADj05mPxOuzjexyW7TfaTOy0/TO3sU4YgyuzxKWLo3mMfr3ykpjYFIzprnj7XtitwCG+gbGqxvLPQppGC5kjwX+yXYRdsqp2RTN0Lv6kdWNDWes5eN9GXqV3DLL4PAF3JiGCIL6gObeG4hGSB2RRgNeIlQr0vscdD9lbUwVT/wpdmqMDDlRM8CrqtcyI+Bm9Nlh2t2Sj326dXk6UsT27i8drx9XDaW+PjBYhHuF+rXf1nEgIi6PxOudcLqDZFr5rsopn/5/+iq3gcCXIKp01LCeCXKceU4inim58/c0I+baaKPLfXDeoPrb3s2vCehKzk5oKst84LuuXVhfEa9QRDUxBvVoAymQrmqfOJaPHwDX4P58Ol1lUKfmAJPsvyEDiAV4pJbnE7wIbMqg6EjFl2g2FSs53EEpMyA/nXnx+u5x1MTFMuEzsNAFiY7iKb2o65qdqfKgaIaNRlKvYScbA5Ij4CSlq9piCZY36N37C9o6NqfMBkzrwoTUceKnVExiQrl2rF5IYYPtqjhU8gf2LqgS5Ydt3008HcD5VvYCbKvgz+hbxIj1+ays4th1EWI4Ec9iLEPzZp1B+5d6GVfWWlOP4ZjC2H3Q7w1wRwuLPnXyF8rDS+9T6i0XGaj0m22WNud7/RJgzBNMWEdSWw2orB5qUanqSjV8Ekgq61LvDPI=
  file_glob: true
  file: out/**/zip/*
  skip_cleanup: true
  on:
    tags: true
